name: "Website"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2

      - name: Install package dependencies
        run: npm install

      - name: Execute test cases
        run: npm run test
        
      - name: Create test build
        run: npm run build
